### ISSUE TITLE
Background-fill Application-icon

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretixdroid#20]
Minor UI thing...

Right now, the `p` in the pretixdroid app icon is a transparent cutout. Works okay - but if the app-drawer has a dark background (for example on the U8000S-devices), the whole icons tends to be just a dark blob.

Proposal that is purely cosmetic: Fill the `p` white.

Going one step further, perhaps even consider putting the whole pretix-icon inside a circle shape (like I did it for the pretixDPC: 
![image](https://user-images.githubusercontent.com/654548/28205416-3811c9dc-6882-11e7-894d-65dfd90ed36a.png)

Again: Purely cosmetic, won't do anything for the functionality of the app itself ;-)

**Comment by raphaelm** [comment]
Yep, that bugged me to already. I think we could put it on a background (so not only fill the p), but I'm not sure how I like our inherently square logo on a circle background, or if we should rather put it on a square. We could also use a purple square with an inverted logo.

(<3 for the DPC logo as a padlock)

**Comment by pc-coholic** [comment]
For a quick and easy mockups: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

![image](https://user-images.githubusercontent.com/654548/28209690-e8426346-6893-11e7-954e-beea5c7222d4.png) ![image](https://user-images.githubusercontent.com/654548/28209704-f4a59dba-6893-11e7-96a6-b09df55e4c6c.png)
![image](https://user-images.githubusercontent.com/654548/28209735-16aa211a-6894-11e7-90ba-7329e22354b6.png) ![image](https://user-images.githubusercontent.com/654548/28209731-1083fb26-6894-11e7-9d6d-f478d82057cc.png)
![image](https://user-images.githubusercontent.com/654548/28209784-4f816eda-6894-11e7-8560-ec17aed64e92.png) ![image](https://user-images.githubusercontent.com/654548/28209796-62a8bb3a-6894-11e7-884c-de7eaa8883f1.png)

**Comment by raphaelm** [comment]
I think I like second row, first column yet. What do you think?

**Comment by pc-coholic** [comment]
Looks good to me :-)
