### ISSUE TITLE
Submit and Add to F-Droid App Repository?

### ISSUE THREAD

**Issue by mattiasaxell** [pretix/pretixdroid#21]
Is it possible to have pretixdroid added to F-droid.org app repositories?

https://f-droid.org/en/contribute/
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

I think there can be many (FOSS) users there who could discover Pretix through that and start using the system it for their events. :smile:

**Comment by raphaelm** [comment]
First of all: In principle, anyone could do that, it wouldn't require us to add it there.

I've got mixed feelings here. While I love the concept of F-Droid, I have had multiple bad experiences with it as a developer. From time to time, a change in the app or in their build toolchain breaks the build and they cannot build new versions of the app any longer without anyone noticing for quite some time. This leads to users running around with old buggy versions without the option to upgrade and us getting error reports about bugs that are long fixed. If we notice it, we often cannot do a lot about it. For example, F-Droid currently has problems with apps that are already built against Android SDK 27.

**Comment by Bubu** [comment]
Added to fdroid here: https://gitlab.com/fdroid/fdroiddata/commit/efa1ce75e6ad4304c11d382aa95b58e4215a0d0b

Should be available within the next few days. Updates should be checked for and build automatically.

**Comment by mattiasaxell** [comment]
Thanks for your reply and reasoning @raphaelm. I understand.

And cool @Bubu adding it, looking forward to see what happens.

I guess that this issue can be closed when/if it is accepted.

**Comment by Bubu** [comment]
I met @raphaelm today in person, so that's how this came to pass. :-)

**Comment by raphaelm** [comment]
Thank you! :)

**Comment by rugk** [comment]
Build stuff can always be fixed. IMHO that's no argument against F-Droid.

Maybe you can also add the "get it on F-Droid" button to your Readme?
And it would also be nice if you could ad screenshots to F-Droid. AFAIK, BTW, this may require some adjustments in this repo.

**Comment by Bubu** [comment]
@rugk are you sure you are in the correct repo?
![image](https://user-images.githubusercontent.com/105185/38567447-879b2df2-3ce6-11e8-89a3-544b38a1178c.png)

**Comment by rugk** [comment]
Ah, yeah, repo. I actually wanted to write website. [Here](https://pretix.eu/about/en/features/checkin) only the Google Play Store is mentioned.

**Comment by raphaelm** [comment]
No, I won't add it to the website. I'm happy that F-Droid exists and pretixdroid can be found there, but from a business perspective I can not recommend it as an official distribution channel of our app, since we don't control it and cannot give the proper level of support. We might in the future run our own F-Droid-compatible repository [as we do for another app already](https://fdroid.rami.io/) if we have a significant number of customers using devices without the Google Play Store.
