### ISSUE TITLE
No tag for v1.11.2

### ISSUE THREAD

**Issue by Bubu** [pretix/pretixdroid#32]
F-Droid build is failing because of this: https://f-droid.org/wiki/page/eu.pretix.pretixdroid/lastbuild_15

**Comment by licaon-kter** [comment]
@raphaelm Could you keep tagging format consistent?  `1.11.2`....`v1.11`

Each time you put an extra `v` or take away one the F-Droid auto update process breaks and no new version is build.

@Bubu FYI https://github.com/pretix/pretixdroid/tags

Ref: https://gitlab.com/fdroid/fdroiddata/commit/5339e70b8b8940f4dd9e5516e014206466562c52

/close this

**Comment by raphaelm** [comment]
Sorry! I tag in so many repos that use different conventions and sometimes get confused. I pushed `v1.11.1`` now as well… Guess I just tag both versions in the future? :see_no_evil:

**Comment by licaon-kter** [comment]
Just one...but look the past ones and keep it the same :)
