### ISSUE TITLE
Provide clear message if wrong event is configured

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretixdroid#35]
I still had my device configured for another event when I tried to scan a ticket. This obviously did not work, but it was not obvious to me what the mismatch was. It would be very helpful if a message is shown that tells me about this error and ideally would allow me to immediately drop the old configuration.

**Comment by raphaelm** [comment]
This is unfortunately impossible, since an app configured to one event *does not know anything* about a secret that is not part of that event. We can't change that either, would be kinda a security problem.

**Comment by DerDakon** [comment]
Can't the QR code simply tell the app which event it is for, which the app can compare with what it is configured for?

**Comment by raphaelm** [comment]
Interesting idea, we need to explore this. However, this would be quite a huge change, since the QR codes currently do not contain any structured data at all and we'd like to stay backwards-compatible there (there are also some users using their very own QR code contents through the API).
