### ISSUE TITLE
Show number of people already checked in

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretixdroid#4]
We should show a counter of how many people are already checked in and how many are to come. We probably first need to add an API in pretix for this.

**Comment by raphaelm** [comment]
I added an API endpoint for this and I also added documentation for the pretixdroid API endpoints: 
https://docs.pretix.eu/en/latest/plugins/pretixdroid.html#get--pretixdroid-api-(organizer)-(event)-status-

cc @jfwiebe :)

**Comment by jfwiebe** [comment]
Work in Progress ;)
@raphaelm Would you mind adding another small endpoint which gives you the event title, organizer and the date of the event? It would be great to show some kind of small event information screen.
![device-2016-12-11-024719](https://cloud.githubusercontent.com/assets/6865786/21077465/5845fb4a-bf4c-11e6-9a58-e50fab6ff0fb.png)

**Comment by raphaelm** [comment]
Uhh, nice! I'll just add this to the status endpoint, give me a minute…

**Comment by raphaelm** [comment]
Done! Docs at https://docs.pretix.eu/en/latest/plugins/pretixdroid.html#get--pretixdroid-api-(organizer)-(event)-status- :)

**Comment by jfwiebe** [comment]
Hey @raphaelm, I am stuck with the GUI. I am not that creative and don't have a single clue about building this interface. Do you have an idea or would like to draw a brief mockup of this interface?

**Comment by raphaelm** [comment]
I would go for a card-based layout like in your example and would fill them for example like this:

![rastergrafik](https://cloud.githubusercontent.com/assets/64280/22731320/7c2731f6-edea-11e6-844d-6bf8e54ab1ca.png)

This is just a draft I randomly came up with, feel free to deviate from it if it makes sense :)

**Comment by jfwiebe** [comment]
Looks great. I will play around and come back with an implementation.

**Comment by raphaelm** [comment]
Hey there :) Let me know if I can help you to get this forward!

**Comment by jfwiebe** [comment]
Hi Raphael, I was not really into my private projects during the last months because I had a theory block at my dual study. I will come up with some results in the following week :)
Best regards, JF

**Comment by raphaelm** [comment]
Alright, no worries, this is not urgent, just wanted to check if everything is fine :)

**Comment by jfwiebe** [comment]
![device-2017-06-16-032353](https://user-images.githubusercontent.com/6865786/27208019-6bb7a770-5243-11e7-9cdb-e76c4d5e1e25.png)
Okay so I created activities, added the status call to the API and also created the ListView with an Adapter that holds these cards. Everything is already parsed so only GUI stuff is left.

**Comment by raphaelm** [comment]
This is awesome! Let me know if there is anything that I can help you with!

**Comment by jfwiebe** [comment]
Thank you - everything is fine. The black cards occur because of some Context-specific thingys... It's fixed now.
![device-2017-06-20-025337](https://user-images.githubusercontent.com/6865786/27311810-e8988264-5563-11e7-8514-77fd663897c7.png)
Some text resizing and item variations are missing. I think, I will leave out the "progress bar" for now. After finishing, I will create a pull request.
